name: Daily Rechtspraak Ingest

on:
  schedule:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ingest:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      DISCOVERY_BATCH_LIMIT: 50000
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run crawler
        run: python crawler.py
      - name: Commit state files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add processed_eclis.json discovery_state.json batch_state.json all_rechtspraak_eclis.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update crawler state"
            git push
          fi
