name: Push 250 Rechtspraak Sample

on:
  workflow_dispatch:

jobs:
  push-sample:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      # Optional – override if you want another repo; otherwise script default is used
      HF_REPO: ${{ secrets.HF_REPO }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install datasets huggingface_hub requests

      - name: Push 250 sample decisions to Hugging Face
        run: python rechtspraak_ingest.py
