name: Import Rechtspraak

on:
  schedule:
    - cron: '15 2 * * *'  # Nightly at 02:15 UTC
  workflow_dispatch:
    inputs:
      limit:
        description: 'Optional: Limit number of documents to ingest'
        required: false
        default: '300'

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ingestion script
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        LIMIT: ${{ github.event.inputs.limit || 300 }}
      run: |
        python rechtspraak_ingest_clean.py
