name: Rechtspraak Sync (Every 30min)

on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 * * * *'

jobs:
  sync-uitspraken:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install datasets huggingface_hub requests

      - name: Run sync script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python rechtspraak_sync.py
