name: Rechtspraak Sync (Every 30min)

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  sync-uitspraken:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawl_rechtspraak.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python crawl_rechtspraak.py \
            --since "$(date -u -d '1 hour ago' +'%Y-%m-%dT%H:%M:%S')" \
            --out data/rs_sync.jsonl \
            --push vGassen/dutch-court-cases-rechtspraak
      - name: Upload crawl shard
        uses: actions/upload-artifact@v3
        with:
          name: crawl-shard
          path: data/rs_sync.jsonl


  merge-and-push:
    needs: sync-uitspraken
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download crawl shard
        uses: actions/download-artifact@v3
        with:
          name: crawl-shard
          path: data


      - name: Run merge_and_push.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python merge_and_push.py
