name: Rechtspraak Sync (Every 30min)

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  sync-uitspraken:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install datasets huggingface_hub requests psutil

      - name: Run rechtspraak_sync.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python rechtspraak_sync.py

  merge-and-push:
    needs: sync-uitspraken
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install datasets huggingface_hub

      - name: Run merge_and_push.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python merge_and_push.py
