name: Scrub and Push to Hugging Face

on:
  workflow_dispatch:

jobs:
  scrub-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scrubbing script
      run: python scrub.py

    - name: Push to Hugging Face Dataset Hub
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        from huggingface_hub import Repository
        repo = Repository(local_dir=".", clone_from="vGassen/dutch-court-cases-rechtspraak", use_auth_token=True)
        repo.push_to_hub()
      shell: python
